/*
  Register definitions for slave core: TDC serializer

  * File           : stdc_wb_slave.h
  * Author         : auto-generated by wbgen2 from stdc_wb_slave.wb
  * Created        : Thu Mar 31 10:59:50 2016
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE stdc_wb_slave.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_STDC_WB_SLAVE_WB
#define __WBGEN2_REGDEFS_STDC_WB_SLAVE_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: FIFO status registers */

/* definitions for field: FIFO not empty in reg: FIFO status registers */
#define STDC_STATUS_NOEMPTY                   WBGEN2_GEN_MASK(0, 1)

/* definitions for field: FIFO overflown in reg: FIFO status registers */
#define STDC_STATUS_OVF                       WBGEN2_GEN_MASK(1, 1)

/* definitions for register: FIFO control registers */

/* definitions for field: Clear FIFO in reg: FIFO control registers */
#define STDC_CTRL_CLR                         WBGEN2_GEN_MASK(0, 1)

/* definitions for field: FIFO Overflown in reg: FIFO control registers */
#define STDC_CTRL_CLR_OVF                     WBGEN2_GEN_MASK(1, 1)

/* definitions for field: FIFO Next in reg: FIFO control registers */
#define STDC_CTRL_NEXT                        WBGEN2_GEN_MASK(2, 1)

/* definitions for field: TDC transitions filter in reg: FIFO control registers */
#define STDC_CTRL_FILTER_MASK                 WBGEN2_GEN_MASK(3, 2)
#define STDC_CTRL_FILTER_SHIFT                3
#define STDC_CTRL_FILTER_W(value)             WBGEN2_GEN_WRITE(value, 3, 2)
#define STDC_CTRL_FILTER_R(reg)               WBGEN2_GEN_READ(reg, 3, 2)

/* definitions for register: FIFO timestamp element */
/* [0x0]: REG FIFO status registers */
#define STDC_REG_STATUS 0x00000000
/* [0x4]: REG FIFO control registers */
#define STDC_REG_CTRL 0x00000004
/* [0x8]: REG FIFO timestamp element */
#define STDC_REG_TDC_DATA 0x00000008
#endif
