---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for DDS RF distribution WB Slave
---------------------------------------------------------------------------------------
-- File           : dds_wbgen2_pkg.vhd
-- Author         : auto-generated by wbgen2 from dds_wb_slave.wb
-- Created        : Tue Apr 28 11:01:31 2015
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE dds_wb_slave.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package dds_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_dds_in_registers is record
    tcr_wr_locked_i                          : std_logic;
    tcr_wr_link_i                            : std_logic;
    tcr_wr_time_valid_i                      : std_logic;
    gpior_pll_sdio_i                         : std_logic;
    gpior_pll_vcxo_sdo_i                     : std_logic;
    pd_data_data_i                           : std_logic_vector(15 downto 0);
    pd_data_valid_i                          : std_logic;
    tune_val_tune_i                          : std_logic_vector(31 downto 0);
    tune_cr_tune_req_i                       : std_logic;
    i2cr_scl_in_i                            : std_logic;
    i2cr_sda_in_i                            : std_logic;
    end record;
  
  constant c_dds_in_registers_init_value: t_dds_in_registers := (
    tcr_wr_locked_i => '0',
    tcr_wr_link_i => '0',
    tcr_wr_time_valid_i => '0',
    gpior_pll_sdio_i => '0',
    gpior_pll_vcxo_sdo_i => '0',
    pd_data_data_i => (others => '0'),
    pd_data_valid_i => '0',
    tune_val_tune_i => (others => '0'),
    tune_cr_tune_req_i => '0',
    i2cr_scl_in_i => '0',
    i2cr_sda_in_i => '0'
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_dds_out_registers is record
      cr_samp_en_o                             : std_logic;
      cr_samp_div_o                            : std_logic_vector(15 downto 0);
      tcr_wr_lock_en_o                         : std_logic;
      gpior_pll_sys_cs_n_o                     : std_logic;
      gpior_pll_sys_reset_n_o                  : std_logic;
      gpior_pll_sclk_o                         : std_logic;
      gpior_pll_sdio_o                         : std_logic;
      gpior_pll_sdio_load_o                    : std_logic;
      gpior_pll_sdio_dir_o                     : std_logic;
      gpior_pll_vcxo_reset_n_o                 : std_logic;
      gpior_pll_vcxo_cs_n_o                    : std_logic;
      gpior_adf_ce_o                           : std_logic;
      gpior_adf_clk_o                          : std_logic;
      gpior_adf_le_o                           : std_logic;
      gpior_adf_data_o                         : std_logic;
      pd_data_valid_o                          : std_logic;
      pd_data_valid_load_o                     : std_logic;
      tune_val_tune_o                          : std_logic_vector(31 downto 0);
      tune_val_tune_load_o                     : std_logic;
      tune_cr_tune_req_o                       : std_logic;
      tune_cr_tune_req_load_o                  : std_logic;
      freq_hi_o                                : std_logic_vector(31 downto 0);
      freq_lo_o                                : std_logic_vector(31 downto 0);
      gain_o                                   : std_logic_vector(15 downto 0);
      rstr_pll_rst_o                           : std_logic;
      rstr_sw_rst_o                            : std_logic;
      i2cr_scl_out_o                           : std_logic;
      i2cr_sda_out_o                           : std_logic;
      end record;
    
    constant c_dds_out_registers_init_value: t_dds_out_registers := (
      cr_samp_en_o => '0',
      cr_samp_div_o => (others => '0'),
      tcr_wr_lock_en_o => '0',
      gpior_pll_sys_cs_n_o => '0',
      gpior_pll_sys_reset_n_o => '0',
      gpior_pll_sclk_o => '0',
      gpior_pll_sdio_o => '0',
      gpior_pll_sdio_load_o => '0',
      gpior_pll_sdio_dir_o => '0',
      gpior_pll_vcxo_reset_n_o => '0',
      gpior_pll_vcxo_cs_n_o => '0',
      gpior_adf_ce_o => '0',
      gpior_adf_clk_o => '0',
      gpior_adf_le_o => '0',
      gpior_adf_data_o => '0',
      pd_data_valid_o => '0',
      pd_data_valid_load_o => '0',
      tune_val_tune_o => (others => '0'),
      tune_val_tune_load_o => '0',
      tune_cr_tune_req_o => '0',
      tune_cr_tune_req_load_o => '0',
      freq_hi_o => (others => '0'),
      freq_lo_o => (others => '0'),
      gain_o => (others => '0'),
      rstr_pll_rst_o => '0',
      rstr_sw_rst_o => '0',
      i2cr_scl_out_o => '0',
      i2cr_sda_out_o => '0'
      );
    function "or" (left, right: t_dds_in_registers) return t_dds_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body dds_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if x = '1' then
return '1';
else
return '0';
end if;
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_dds_in_registers) return t_dds_in_registers is
variable tmp: t_dds_in_registers;
begin
tmp.tcr_wr_locked_i := f_x_to_zero(left.tcr_wr_locked_i) or f_x_to_zero(right.tcr_wr_locked_i);
tmp.tcr_wr_link_i := f_x_to_zero(left.tcr_wr_link_i) or f_x_to_zero(right.tcr_wr_link_i);
tmp.tcr_wr_time_valid_i := f_x_to_zero(left.tcr_wr_time_valid_i) or f_x_to_zero(right.tcr_wr_time_valid_i);
tmp.gpior_pll_sdio_i := f_x_to_zero(left.gpior_pll_sdio_i) or f_x_to_zero(right.gpior_pll_sdio_i);
tmp.gpior_pll_vcxo_sdo_i := f_x_to_zero(left.gpior_pll_vcxo_sdo_i) or f_x_to_zero(right.gpior_pll_vcxo_sdo_i);
tmp.pd_data_data_i := f_x_to_zero(left.pd_data_data_i) or f_x_to_zero(right.pd_data_data_i);
tmp.pd_data_valid_i := f_x_to_zero(left.pd_data_valid_i) or f_x_to_zero(right.pd_data_valid_i);
tmp.tune_val_tune_i := f_x_to_zero(left.tune_val_tune_i) or f_x_to_zero(right.tune_val_tune_i);
tmp.tune_cr_tune_req_i := f_x_to_zero(left.tune_cr_tune_req_i) or f_x_to_zero(right.tune_cr_tune_req_i);
tmp.i2cr_scl_in_i := f_x_to_zero(left.i2cr_scl_in_i) or f_x_to_zero(right.i2cr_scl_in_i);
tmp.i2cr_sda_in_i := f_x_to_zero(left.i2cr_sda_in_i) or f_x_to_zero(right.i2cr_sda_in_i);
return tmp;
end function;
end package body;
