---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for TrevGen
---------------------------------------------------------------------------------------
-- File           : TrevGen_wbgen2_pkg.vhd
-- Author         : auto-generated by wbgen2 from TrevGen_wb_slave.wb
-- Created        : Fri Jan 13 12:41:41 2017
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE TrevGen_wb_slave.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package TrevGen_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_TrevGen_in_registers is record
    trevgen_lc_next_tick_i                   : std_logic_vector(31 downto 0);
    trevgen_lc_trev_i                        : std_logic_vector(31 downto 0);
    end record;
  
  constant c_TrevGen_in_registers_init_value: t_TrevGen_in_registers := (
    trevgen_lc_next_tick_i => (others => '0'),
    trevgen_lc_trev_i => (others => '0')
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_TrevGen_out_registers is record
      trevgen_rm_next_tick_o                   : std_logic_vector(31 downto 0);
      trevgen_rm_trev_o                        : std_logic_vector(31 downto 0);
      trevgen_strobe_p_o                       : std_logic;
      end record;
    
    constant c_TrevGen_out_registers_init_value: t_TrevGen_out_registers := (
      trevgen_rm_next_tick_o => (others => '0'),
      trevgen_rm_trev_o => (others => '0'),
      trevgen_strobe_p_o => '0'
      );
    function "or" (left, right: t_TrevGen_in_registers) return t_TrevGen_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body TrevGen_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if x = '1' then
return '1';
else
return '0';
end if;
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_TrevGen_in_registers) return t_TrevGen_in_registers is
variable tmp: t_TrevGen_in_registers;
begin
tmp.trevgen_lc_next_tick_i := f_x_to_zero(left.trevgen_lc_next_tick_i) or f_x_to_zero(right.trevgen_lc_next_tick_i);
tmp.trevgen_lc_trev_i := f_x_to_zero(left.trevgen_lc_trev_i) or f_x_to_zero(right.trevgen_lc_trev_i);
return tmp;
end function;
end package body;
