/*
  Register definitions for slave core: TrevGen

  * File           : ../wb/TrevGen_wb_slave.h
  * Author         : auto-generated by wbgen2 from TrevGen_wb_slave.wb
  * Created        : Wed Jul 20 19:34:44 2016
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE TrevGen_wb_slave.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_TREVGEN_WB_SLAVE_WB
#define __WBGEN2_REGDEFS_TREVGEN_WB_SLAVE_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Remote next Trev tick time Stamp */

/* definitions for register: LC_NextTick */

/* definitions for register: RM_Trev */

/* definitions for register: LC_Trev */

/* definitions for register: Strobe_p */
/* [0x0]: REG Remote next Trev tick time Stamp */
#define TREVGEN_REG_RM_NEXT_TICK 0x00000000
/* [0x4]: REG LC_NextTick */
#define TREVGEN_REG_LC_NEXT_TICK 0x00000004
/* [0x8]: REG RM_Trev */
#define TREVGEN_REG_RM_TREV 0x00000008
/* [0xc]: REG LC_Trev */
#define TREVGEN_REG_LC_TREV 0x0000000c
/* [0x10]: REG Strobe_p */
#define TREVGEN_REG_STROBE_P 0x00000010
#endif
