/*
  Register definitions for slave core: D3S Acquisition buffer

  * File           : d3s_acq_buffer_wb.h
  * Author         : auto-generated by wbgen2 from d3s_acq_buffer_wb.wb
  * Created        : Wed Aug 24 12:03:30 2016
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE d3s_acq_buffer_wb.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_D3S_ACQ_BUFFER_WB_WB
#define __WBGEN2_REGDEFS_D3S_ACQ_BUFFER_WB_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Control Reg */

/* definitions for field: Start sampling in reg: Control Reg */
#define ACQ_CR_START                          WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Ready in reg: Control Reg */
#define ACQ_CR_READY                          WBGEN2_GEN_MASK(1, 1)

/* definitions for register: Buffer address */

/* definitions for register: Buffer data */
/* [0x0]: REG Control Reg */
#define ACQ_REG_CR 0x00000000
/* [0x4]: REG Buffer address */
#define ACQ_REG_ADDR 0x00000004
/* [0x8]: REG Buffer data */
#define ACQ_REG_DATA 0x00000008
#endif
