onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group VME /main/VME/sys_rst_n_i
add wave -noupdate -group VME /main/VME/as_n
add wave -noupdate -group VME /main/VME/rst_n
add wave -noupdate -group VME /main/VME/write_n
add wave -noupdate -group VME /main/VME/am
add wave -noupdate -group VME -expand /main/VME/ds_n
add wave -noupdate -group VME /main/VME/ga
add wave -noupdate -group VME /main/VME/berr_n
add wave -noupdate -group VME /main/VME/dtack_n
add wave -noupdate -group VME /main/VME/retry_n
add wave -noupdate -group VME /main/VME/lword_n
add wave -noupdate -group VME /main/VME/addr
add wave -noupdate -group VME /main/VME/data
add wave -noupdate -group VME /main/VME/bbsy_n
add wave -noupdate -group VME /main/VME/irq_n
add wave -noupdate -group VME /main/VME/iackin_n
add wave -noupdate -group VME /main/VME/iackout_n
add wave -noupdate -group VME /main/VME/iack_n
add wave -noupdate -group VME /main/VME/q_as_n
add wave -noupdate -group VME /main/VME/q_rst_n
add wave -noupdate -group VME /main/VME/q_write_n
add wave -noupdate -group VME /main/VME/q_am
add wave -noupdate -group VME /main/VME/q_ds_n
add wave -noupdate -group VME /main/VME/q_ga
add wave -noupdate -group VME /main/VME/q_berr_n
add wave -noupdate -group VME /main/VME/q_dtack_n
add wave -noupdate -group VME /main/VME/q_retry_n
add wave -noupdate -group VME /main/VME/q_lword_n
add wave -noupdate -group VME /main/VME/q_addr
add wave -noupdate -group VME /main/VME/q_data
add wave -noupdate -group VME /main/VME/q_bbsy_n
add wave -noupdate -group VME /main/VME/q_irq_n
add wave -noupdate -group VME /main/VME/q_iackin_n
add wave -noupdate -group VME /main/VME/q_iackout_n
add wave -noupdate -group VME /main/VME/q_iack_n
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_sys_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_dmtd_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_ref_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_aux_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_ext_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/pps_ext_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/rst_n_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_hpll_load_p1_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_hpll_data_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_dpll_load_p1_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_dpll_data_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_ref_clk_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_tx_data_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_tx_k_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_tx_disparity_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_tx_enc_err_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_rx_data_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_rx_rbclk_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_rx_k_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_rx_enc_err_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_rx_bitslide_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_rst_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/phy_loopen_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/led_act_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/led_link_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/scl_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/scl_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sda_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sda_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sfp_scl_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sfp_scl_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sfp_sda_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sfp_sda_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sfp_det_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/btn1_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/btn2_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/uart_rxd_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/uart_txd_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/owr_pwren_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/owr_en_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/owr_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_adr_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_dat_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_dat_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_sel_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_we_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_cyc_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_stb_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_ack_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_err_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_rty_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/wb_stall_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_adr_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_dat_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_dat_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_sel_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_we_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_cyc_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_stb_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_ack_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/aux_stall_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_adr_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_dat_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_sel_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_cyc_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_we_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_stb_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_ack_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_err_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_snk_stall_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_adr_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_dat_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_sel_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_cyc_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_stb_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_we_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_ack_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_err_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_src_stall_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/txtsu_port_id_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/txtsu_frame_id_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/txtsu_ts_value_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/txtsu_ts_incorrect_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/txtsu_stb_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/txtsu_ack_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_link_up_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_dac_value_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_dac_wr_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_clk_aux_lock_en_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_clk_aux_locked_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_time_valid_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_tai_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/tm_cycles_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/pps_p_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/pps_led_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dio_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/rst_aux_n_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/link_ok_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/rst_wrc_n
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/rst_net_n
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/s_pps_csync
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/pps_valid
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ppsg_wb_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ppsg_wb_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/spll_wb_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/spll_wb_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_txtsu_port_id
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_txtsu_frame_id
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_txtsu_ts_value
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_txtsu_ts_incorrect
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_txtsu_stb
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_txtsu_ack
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_led_link
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mnic_mem_data_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mnic_mem_addr_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mnic_mem_data_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mnic_mem_wr_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mnic_txtsu_ack
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dpram_wbb_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dpram_wbb_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/periph_slave_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/periph_slave_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sysc_in_regs
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/sysc_out_regs
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/secbar_master_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/secbar_master_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/cbar_slave_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/cbar_slave_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/cbar_master_i
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/cbar_master_o
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_wb_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ext_wb_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/hpll_auxout
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dmpll_auxout
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_ref_slv
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_rx_slv
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/s_dummy_addr
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/softpll_irq
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/lm32_irq_slv
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_wb_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_wb_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/minic_wb_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/minic_wb_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_src_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_src_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_snk_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/ep_snk_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mux_src_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mux_src_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mux_snk_out
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mux_snk_in
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/mux_class
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dummy
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/spll_out_locked
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_dpll_data
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_dpll_sel
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/dac_dpll_load_p1
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/clk_fb
add wave -noupdate -group WRPC /main/DUT/U_Node_Template/U_WR_CORE/WRPC/out_enable
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/clk_sys_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/rst_sys_n_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/rst_n_a_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_sclk_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_sdi_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_cs_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_dac_sync_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_sdo_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_status_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_clk_125m_p_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_clk_125m_n_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/acam_refclk_p_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/acam_refclk_n_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/start_from_fpga_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/err_flag_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/int_flag_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/start_dis_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/stop_dis_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/data_bus_io
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/address_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/cs_n_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/oe_n_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/rd_n_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/wr_n_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/ef1_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/ef2_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/enable_inputs_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/term_en_1_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/term_en_2_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/term_en_3_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/term_en_4_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/term_en_5_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_led_status_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_led_trig1_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_led_trig2_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_led_trig3_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_led_trig4_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_led_trig5_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_in_fpga_1_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_in_fpga_2_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_in_fpga_3_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_in_fpga_4_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_in_fpga_5_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/mezz_scl_b
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/mezz_sda_b
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/mezz_one_wire_b
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_link_up_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_time_valid_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_cycles_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_tai_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_clk_aux_lock_en_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_clk_aux_locked_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_clk_dmtd_locked_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_dac_value_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tm_dac_wr_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/slave_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/slave_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/direct_slave_i
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/direct_slave_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/irq_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/clk_125m_tdc_o
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/clk_62m5_sys
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/clk_125m_mezz
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/rst_125m_mezz_n
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/rst_125m_mezz
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/acam_refclk_r_edge_p
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/send_dac_word_p
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/dac_word
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_sclk
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_sdi
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/pll_dac_sync
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/fmc_eic_irq
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/fmc_eic_irq_synch
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_scl_out
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_scl_oen
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_sda_out
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/tdc_sda_oen
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/direct_timestamp
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/direct_timestamp_wr
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/cnx_master_in
add wave -noupdate -group TDCWrap /main/DUT/U_TDC_Core/cnx_master_out
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/clk_sys_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/rst_sys_n_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/clk_tdc_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/rst_tdc_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/acam_refclk_r_edge_p_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/send_dac_word_p_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/dac_word_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/start_from_fpga_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/err_flag_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/int_flag_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/start_dis_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/stop_dis_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/data_bus_io
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/address_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/cs_n_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/oe_n_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/rd_n_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wr_n_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/ef1_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/ef2_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/enable_inputs_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/term_en_1_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/term_en_2_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/term_en_3_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/term_en_4_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/term_en_5_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_led_status_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_led_trig1_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_led_trig2_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_led_trig3_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_led_trig4_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_led_trig5_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_in_fpga_1_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_in_fpga_2_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_in_fpga_3_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_in_fpga_4_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_in_fpga_5_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_link_up_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_time_valid_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_cycles_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_utc_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_clk_aux_lock_en_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_clk_aux_locked_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_clk_dmtd_locked_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_dac_value_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_dac_wr_p_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/slave_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/slave_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wb_irq_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/i2c_scl_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/i2c_scl_oen_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/i2c_scl_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/i2c_sda_oen_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/i2c_sda_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/i2c_sda_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/onewire_b
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/direct_timestamp_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/direct_timestamp_stb_o
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/general_rst_n
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/rst_ref_0_n
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/cnx_master_out
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/cnx_master_in
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_core_wb_adr
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/tdc_mem_wb_adr
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/mezz_owr_en
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/mezz_owr_i
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/sys_scl_in
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/sys_scl_out
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/sys_scl_oe_n
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/sys_sda_in
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/sys_sda_out
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/sys_sda_oe_n
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/irq_tstamp_p
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/irq_time_p
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/irq_acam_err_p
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/irq_tstamp_p_sys
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/irq_time_p_sys
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/irq_acam_err_p_sys
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/reg_to_wr
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/reg_from_wr
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_utc_p
add wave -noupdate -group TDCMezz /main/DUT/U_TDC_Core/cmp_tdc_mezz/wrabbit_synched
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/clk_sys_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/rst_n_sys_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/clk_tdc_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/rst_tdc_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_refclk_r_edge_p_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/send_dac_word_p_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/dac_word_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/start_from_fpga_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/err_flag_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/int_flag_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/start_dis_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/stop_dis_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/data_bus_io
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/address_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/cs_n_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/oe_n_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/rd_n_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wr_n_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/ef1_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/ef2_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/enable_inputs_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/term_en_1_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/term_en_2_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/term_en_3_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/term_en_4_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/term_en_5_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_led_status_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_led_trig1_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_led_trig2_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_led_trig3_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_led_trig4_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_led_trig5_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_1_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_2_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_3_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_4_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_5_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/irq_tstamp_p_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/irq_time_p_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/irq_acam_err_p_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wrabbit_status_reg_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wrabbit_ctrl_reg_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wrabbit_synched_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wrabbit_tai_p_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wrabbit_tai_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/cfg_slave_i
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/cfg_slave_o
add wave -noupdate -group TDCCore -expand /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/mem_slave_i
add wave -noupdate -group TDCCore -expand /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/mem_slave_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/direct_timestamp_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/direct_timestamp_stb_o
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_adr
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_cyc
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_stb
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_we
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_ack
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_dat_r
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acm_dat_w
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_ef1
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_ef2
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_ef1_meta
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_ef2_meta
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_errflag_f_edge_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_errflag_r_edge_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_intflag_f_edge_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_tstamp1
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_tstamp2
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_tstamp1_ok_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_tstamp2_ok_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/activate_acq_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/deactivate_acq_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/load_acam_config
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/read_acam_config
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/read_acam_status
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/read_ififo1
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/read_ififo2
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/read_start01
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reset_acam
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/load_utc
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/clear_dacapo_counter
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/roll_over_incr_recent
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/deactivate_chan
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/pulse_delay
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/window_delay
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/clk_period
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/starting_utc
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_inputs_en
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_ififo1
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_ififo2
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_start01
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/irq_tstamp_threshold
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/irq_time_threshold
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/local_utc
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wr_index
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_config
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_config_rdbk
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tstamp_wr_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/start_from_fpga
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/state_active_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/clk_i_cycles_offset
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/roll_over_nb
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/retrig_nb_offset
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/local_utc_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/current_retrig_nb
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/utc_p
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/utc
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/wrabbit_ctrl_reg
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_adr
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_stb
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_cyc
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_we
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_ack
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_data_wr
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circ_buff_class_data_rd
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_channel
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_1
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_2
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_3
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_4
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/tdc_in_fpga_5
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/acam_tstamp_channel
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/rst_sys
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/CONTROL
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/CLK
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/TRIG0
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/TRIG1
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/TRIG2
add wave -noupdate -group TDCCore /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/TRIG3
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/clk_sys_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/rst_n_sys_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/clk_tdc_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/rst_tdc_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/slave_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/slave_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_config_rdbk_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_ififo1_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_ififo2_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_start01_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/wr_index_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/local_utc_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/core_status_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/irq_code_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/wrabbit_status_reg_i
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_config_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/activate_acq_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/deactivate_acq_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_wr_config_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_rdbk_config_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_rst_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_rdbk_status_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_rdbk_ififo1_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_rdbk_ififo2_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_rdbk_start01_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dacapo_c_rst_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/deactivate_chan_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/send_dac_word_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dac_word_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/load_utc_p_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/starting_utc_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/irq_tstamp_threshold_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/irq_time_threshold_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/one_hz_phase_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_inputs_en_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/wrabbit_ctrl_reg_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/start_phase_o
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_config
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/reg_adr
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/reg_adr_pipe0
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/starting_utc
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/acam_inputs_en
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/start_phase
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/ctrl_reg
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/one_hz_phase
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/irq_tstamp_threshold
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/irq_time_threshold
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/clear_ctrl_reg
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/send_dac_word_p
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dac_word
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/pulse_extender_en
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/pulse_extender_c
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/wrabbit_ctrl_reg
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/deactivate_chan
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/ack_out_pipe0
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/ack_out_pipe1
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_comb0
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_comb1
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_comb2
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_comb3
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_pipe0
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_pipe1
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_pipe2
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/dat_out_pipe3
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/cyc_in_progress
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/wb_in
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/wb_out
add wave -noupdate -group TDC_Regs /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/reg_control_block/rst_n_tdc
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/clk_tdc_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/clk_sys_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_rst_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_stb_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_cyc_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_we_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_adr_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_dat_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_rst_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_stb_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_cyc_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_we_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_adr_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_dat_i
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_ack_p_o
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_dat_o
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_ack_o
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_dat_o
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tdc_mem_wb_stall_o
add wave -noupdate -group CircBuf -height 16 /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_rd_wb_st
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/nxt_tstamp_rd_wb_st
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_ack_p
add wave -noupdate -group CircBuf -expand /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_rd_we
add wave -noupdate -group CircBuf /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_tdc_core/circular_buffer_block/tstamp_wr_we
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/clk_sys_i
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/rst_n_i
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/slave_i
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/slave_o
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/desc_o
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/owr_pwren_o
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/owr_en_o
add wave -noupdate -expand -group OneWire /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_fmc_onewire/owr_i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {258866163940 fs} 0}
configure wave -namecolwidth 234
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {258246098320 fs} {259457901680 fs}
