onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/clk_i
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/reset
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/mainFSMreset
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader0
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader1
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader2
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader3
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader4
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader5
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader6
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Ader7
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap0
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap1
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap2
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap3
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap4
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap5
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap6
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmCap7
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap0
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap1
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap2
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap3
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap4
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap5
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap6
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAmCap7
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/Am
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/XAm
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/DFS_i
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/decode
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/AmMatch
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/s_FUNC_ADER
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/s_FUNC_AMCAP
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/s_FUNC_XAMCAP
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/s_amcap_match
add wave -noupdate -group AM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Am_Match/s_xamcap_match
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/clk_i
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/reset
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/decode
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/mainFSMreset
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Addr
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/AddrWidth
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader0
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader1
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader2
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader3
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader4
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader5
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader6
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Ader7
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem0
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem1
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem2
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem3
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem4
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem5
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem6
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Adem7
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/FunctMatch
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/DFS_o
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/Nx_Base_Addr
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/s_FUNC_ADER
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/s_FUNC_ADEM
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/s_FUNC_ADER_64
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/s_FUNC_ADEM_64
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/s_isprev_func64
add wave -noupdate -group FM /main/DUT/U_Node_Template/U_VME_Core/U_Wrapped_VME/Inst_VME_bus/Inst_Access_Decode/Inst_Funct_Match/s_locAddr
add wave -noupdate -group VME /main/VME/sys_rst_n_i
add wave -noupdate -group VME /main/VME/as_n
add wave -noupdate -group VME /main/VME/rst_n
add wave -noupdate -group VME /main/VME/write_n
add wave -noupdate -group VME /main/VME/am
add wave -noupdate -group VME /main/VME/ds_n
add wave -noupdate -group VME /main/VME/ga
add wave -noupdate -group VME /main/VME/berr_n
add wave -noupdate -group VME /main/VME/dtack_n
add wave -noupdate -group VME /main/VME/retry_n
add wave -noupdate -group VME /main/VME/lword_n
add wave -noupdate -group VME /main/VME/addr
add wave -noupdate -group VME /main/VME/data
add wave -noupdate -group VME /main/VME/bbsy_n
add wave -noupdate -group VME /main/VME/irq_n
add wave -noupdate -group VME /main/VME/iackin_n
add wave -noupdate -group VME /main/VME/iackout_n
add wave -noupdate -group VME /main/VME/iack_n
add wave -noupdate -group VME /main/VME/q_as_n
add wave -noupdate -group VME /main/VME/q_rst_n
add wave -noupdate -group VME /main/VME/q_write_n
add wave -noupdate -group VME /main/VME/q_am
add wave -noupdate -group VME /main/VME/q_ds_n
add wave -noupdate -group VME /main/VME/q_ga
add wave -noupdate -group VME /main/VME/q_berr_n
add wave -noupdate -group VME /main/VME/q_dtack_n
add wave -noupdate -group VME /main/VME/q_retry_n
add wave -noupdate -group VME /main/VME/q_lword_n
add wave -noupdate -group VME /main/VME/q_addr
add wave -noupdate -group VME /main/VME/q_data
add wave -noupdate -group VME /main/VME/q_bbsy_n
add wave -noupdate -group VME /main/VME/q_irq_n
add wave -noupdate -group VME /main/VME/q_iackin_n
add wave -noupdate -group VME /main/VME/q_iackout_n
add wave -noupdate -group VME /main/VME/q_iack_n
add wave -noupdate -group Top /main/DUT/rst_n_a_i
add wave -noupdate -group Top /main/DUT/clk_20m_vcxo_i
add wave -noupdate -group Top /main/DUT/clk_125m_pllref_p_i
add wave -noupdate -group Top /main/DUT/clk_125m_pllref_n_i
add wave -noupdate -group Top /main/DUT/clk_125m_gtp_p_i
add wave -noupdate -group Top /main/DUT/clk_125m_gtp_n_i
add wave -noupdate -group Top /main/DUT/fp_led_line_oen_o
add wave -noupdate -group Top /main/DUT/fp_led_line_o
add wave -noupdate -group Top /main/DUT/fp_led_column_o
add wave -noupdate -group Top /main/DUT/fp_gpio1_a2b_o
add wave -noupdate -group Top /main/DUT/fp_gpio2_a2b_o
add wave -noupdate -group Top /main/DUT/fp_gpio34_a2b_o
add wave -noupdate -group Top /main/DUT/fp_gpio1_b
add wave -noupdate -group Top /main/DUT/fp_gpio2_b
add wave -noupdate -group Top /main/DUT/fp_gpio3_b
add wave -noupdate -group Top /main/DUT/fp_gpio4_b
add wave -noupdate -group Top /main/DUT/VME_AS_n_i
add wave -noupdate -group Top /main/DUT/VME_RST_n_i
add wave -noupdate -group Top /main/DUT/VME_WRITE_n_i
add wave -noupdate -group Top /main/DUT/VME_AM_i
add wave -noupdate -group Top /main/DUT/VME_DS_n_i
add wave -noupdate -group Top /main/DUT/VME_GA_i
add wave -noupdate -group Top /main/DUT/VME_BERR_o
add wave -noupdate -group Top /main/DUT/VME_DTACK_n_o
add wave -noupdate -group Top /main/DUT/VME_RETRY_n_o
add wave -noupdate -group Top /main/DUT/VME_RETRY_OE_o
add wave -noupdate -group Top /main/DUT/VME_LWORD_n_b
add wave -noupdate -group Top /main/DUT/VME_ADDR_b
add wave -noupdate -group Top /main/DUT/VME_DATA_b
add wave -noupdate -group Top /main/DUT/VME_BBSY_n_i
add wave -noupdate -group Top /main/DUT/VME_IRQ_n_o
add wave -noupdate -group Top /main/DUT/VME_IACK_n_i
add wave -noupdate -group Top /main/DUT/VME_IACKIN_n_i
add wave -noupdate -group Top /main/DUT/VME_IACKOUT_n_o
add wave -noupdate -group Top /main/DUT/VME_DTACK_OE_o
add wave -noupdate -group Top /main/DUT/VME_DATA_DIR_o
add wave -noupdate -group Top /main/DUT/VME_DATA_OE_N_o
add wave -noupdate -group Top /main/DUT/VME_ADDR_DIR_o
add wave -noupdate -group Top /main/DUT/VME_ADDR_OE_N_o
add wave -noupdate -group Top /main/DUT/sfp_txp_o
add wave -noupdate -group Top /main/DUT/sfp_txn_o
add wave -noupdate -group Top /main/DUT/sfp_rxp_i
add wave -noupdate -group Top /main/DUT/sfp_rxn_i
add wave -noupdate -group Top /main/DUT/sfp_mod_def0_b
add wave -noupdate -group Top /main/DUT/sfp_mod_def1_b
add wave -noupdate -group Top /main/DUT/sfp_mod_def2_b
add wave -noupdate -group Top /main/DUT/sfp_rate_select_b
add wave -noupdate -group Top /main/DUT/sfp_tx_fault_i
add wave -noupdate -group Top /main/DUT/sfp_tx_disable_o
add wave -noupdate -group Top /main/DUT/sfp_los_i
add wave -noupdate -group Top /main/DUT/pll20dac_din_o
add wave -noupdate -group Top /main/DUT/pll20dac_sclk_o
add wave -noupdate -group Top /main/DUT/pll20dac_sync_n_o
add wave -noupdate -group Top /main/DUT/pll25dac_din_o
add wave -noupdate -group Top /main/DUT/pll25dac_sclk_o
add wave -noupdate -group Top /main/DUT/pll25dac_sync_n_o
add wave -noupdate -group Top /main/DUT/fmc0_prsntm2c_n_i
add wave -noupdate -group Top /main/DUT/fmc1_prsntm2c_n_i
add wave -noupdate -group Top /main/DUT/fmc0_scl_b
add wave -noupdate -group Top /main/DUT/fmc0_sda_b
add wave -noupdate -group Top /main/DUT/fmc1_scl_b
add wave -noupdate -group Top /main/DUT/fmc1_sda_b
add wave -noupdate -group Top /main/DUT/tempid_dq_b
add wave -noupdate -group Top /main/DUT/uart_rxd_i
add wave -noupdate -group Top /main/DUT/uart_txd_o
add wave -noupdate -group Top /main/DUT/clk_sys
add wave -noupdate -group Top /main/DUT/rst_n
add wave -noupdate -group Top /main/DUT/fmc1_wb_out
add wave -noupdate -group Top /main/DUT/fmc1_wb_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/rst_n_a_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/rst_n_sys_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_sys_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_20m_vcxo_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_125m_pllref_p_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_125m_pllref_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_125m_gtp_p_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_125m_gtp_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_led_line_oen_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_led_line_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_led_column_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio1_a2b_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio2_a2b_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio34_a2b_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio1_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio2_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio3_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fp_gpio4_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_AS_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_RST_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_WRITE_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_AM_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DS_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_GA_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_BERR_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DTACK_n_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_RETRY_n_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_RETRY_OE_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_LWORD_n_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_ADDR_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DATA_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_BBSY_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_IRQ_n_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_IACK_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_IACKIN_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_IACKOUT_n_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DTACK_OE_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DATA_DIR_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DATA_OE_N_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_ADDR_DIR_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_ADDR_OE_N_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_txp_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_txn_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_rxp_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_rxn_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_mod_def0_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_mod_def1_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_mod_def2_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_rate_select_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_tx_fault_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_tx_disable_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_los_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pll20dac_din_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pll20dac_sclk_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pll20dac_sync_n_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pll25dac_din_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pll25dac_sclk_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pll25dac_sync_n_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fmc0_prsntm2c_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fmc1_prsntm2c_n_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tempid_dq_b
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/uart_rxd_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/uart_txd_o
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fmc0_clk_aux_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/fmc1_clk_aux_i
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DATA_b_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_ADDR_b_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_LWORD_n_b_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_DATA_DIR_int
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/VME_ADDR_DIR_int
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/dac_hpll_load_p1
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/dac_dpll_load_p1
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/dac_hpll_data
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/dac_dpll_data
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_tx_data
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_tx_k
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_tx_disparity
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_tx_enc_err
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_rx_data
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_rx_rbclk
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_rx_k
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_rx_enc_err
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_rx_bitslide
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_rst
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/phy_loopen
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/cnx_master_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/cnx_master_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/cnx_slave_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/cnx_slave_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrn_fmc0_wb_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrn_fmc1_wb_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_aux_master_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrn_fmc0_wb_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrn_fmc1_wb_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_aux_master_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_link_up
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_tai
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_cycles
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_time_valid
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_clk_aux_lock_en
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_clk_aux_locked
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_dac_value
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm_dac_wr
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_scl_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_scl_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_sda_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_sda_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_scl_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_scl_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_sda_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sfp_sda_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_owr_en
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrc_owr_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pllout_clk_sys
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pllout_clk_dmtd
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pllout_clk_fb_pllref
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pllout_clk_fb_dmtd
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_20m_vcxo_buf
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_125m_pllref
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_125m_gtp
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_sys
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/clk_dmtd
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/local_reset_n
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/wrn_irq
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pins
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pps
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/vic_master_irq
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/ebm_src_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/ebm_src_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/ebs_snk_in
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/ebs_snk_out
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/powerup_reset_cnt
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/powerup_rst_n
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/sys_locked
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/led_state
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pps_led
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/pps_ext
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/led_link
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/led_act
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/vme_access
add wave -noupdate -group Node-TMPL /main/DUT/U_Node_Template/tm
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/clk_i
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/rst_n_i
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/sp_master_o
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/sp_master_i
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/dp_master_o
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/dp_master_i
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/ebm_master_o
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/ebm_master_i
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/ebs_slave_o
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/ebs_slave_i
add wave -noupdate -group WRNC -expand /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/host_slave_i
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/host_slave_o
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/host_irq_o
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/tm_i
add wave -noupdate -group WRNC -expand -subitemconfig {/main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/hac_master_out(0) -expand} /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/hac_master_out
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/hac_master_in
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/si_slave_in
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/si_slave_out
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/si_master_in
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/si_master_out
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/cpu_csr_fromwb
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/cpu_csr_towb
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/hmq_status
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/rmq_status
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/timing
add wave -noupdate -group WRNC /main/DUT/U_Node_Template/U_WR_Node/U_WRNode_Core/cpu_index
add wave -noupdate -group SvecTpo /main/DUT/rst_n_a_i
add wave -noupdate -group SvecTpo /main/DUT/clk_20m_vcxo_i
add wave -noupdate -group SvecTpo /main/DUT/clk_125m_pllref_p_i
add wave -noupdate -group SvecTpo /main/DUT/clk_125m_pllref_n_i
add wave -noupdate -group SvecTpo /main/DUT/clk_125m_gtp_p_i
add wave -noupdate -group SvecTpo /main/DUT/clk_125m_gtp_n_i
add wave -noupdate -group SvecTpo /main/DUT/fp_led_line_oen_o
add wave -noupdate -group SvecTpo /main/DUT/fp_led_line_o
add wave -noupdate -group SvecTpo /main/DUT/fp_led_column_o
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio1_a2b_o
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio2_a2b_o
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio34_a2b_o
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio1_b
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio2_b
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio3_b
add wave -noupdate -group SvecTpo /main/DUT/fp_gpio4_b
add wave -noupdate -group SvecTpo /main/DUT/dbg_led0_o
add wave -noupdate -group SvecTpo /main/DUT/dbg_led1_o
add wave -noupdate -group SvecTpo /main/DUT/dbg_led2_o
add wave -noupdate -group SvecTpo /main/DUT/dbg_led3_o
add wave -noupdate -group SvecTpo /main/DUT/carrier_scl_b
add wave -noupdate -group SvecTpo /main/DUT/carrier_sda_b
add wave -noupdate -group SvecTpo /main/DUT/VME_AS_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_RST_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_WRITE_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_AM_i
add wave -noupdate -group SvecTpo /main/DUT/VME_DS_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_GA_i
add wave -noupdate -group SvecTpo /main/DUT/VME_BERR_o
add wave -noupdate -group SvecTpo /main/DUT/VME_DTACK_n_o
add wave -noupdate -group SvecTpo /main/DUT/VME_RETRY_n_o
add wave -noupdate -group SvecTpo /main/DUT/VME_RETRY_OE_o
add wave -noupdate -group SvecTpo /main/DUT/VME_LWORD_n_b
add wave -noupdate -group SvecTpo /main/DUT/VME_ADDR_b
add wave -noupdate -group SvecTpo /main/DUT/VME_DATA_b
add wave -noupdate -group SvecTpo /main/DUT/VME_BBSY_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_IRQ_n_o
add wave -noupdate -group SvecTpo /main/DUT/VME_IACK_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_IACKIN_n_i
add wave -noupdate -group SvecTpo /main/DUT/VME_IACKOUT_n_o
add wave -noupdate -group SvecTpo /main/DUT/VME_DTACK_OE_o
add wave -noupdate -group SvecTpo /main/DUT/VME_DATA_DIR_o
add wave -noupdate -group SvecTpo /main/DUT/VME_DATA_OE_N_o
add wave -noupdate -group SvecTpo /main/DUT/VME_ADDR_DIR_o
add wave -noupdate -group SvecTpo /main/DUT/VME_ADDR_OE_N_o
add wave -noupdate -group SvecTpo /main/DUT/sfp_txp_o
add wave -noupdate -group SvecTpo /main/DUT/sfp_txn_o
add wave -noupdate -group SvecTpo /main/DUT/sfp_rxp_i
add wave -noupdate -group SvecTpo /main/DUT/sfp_rxn_i
add wave -noupdate -group SvecTpo /main/DUT/sfp_mod_def0_b
add wave -noupdate -group SvecTpo /main/DUT/sfp_mod_def1_b
add wave -noupdate -group SvecTpo /main/DUT/sfp_mod_def2_b
add wave -noupdate -group SvecTpo /main/DUT/sfp_rate_select_b
add wave -noupdate -group SvecTpo /main/DUT/sfp_tx_fault_i
add wave -noupdate -group SvecTpo /main/DUT/sfp_tx_disable_o
add wave -noupdate -group SvecTpo /main/DUT/sfp_los_i
add wave -noupdate -group SvecTpo /main/DUT/pll20dac_din_o
add wave -noupdate -group SvecTpo /main/DUT/pll20dac_sclk_o
add wave -noupdate -group SvecTpo /main/DUT/pll20dac_sync_n_o
add wave -noupdate -group SvecTpo /main/DUT/pll25dac_din_o
add wave -noupdate -group SvecTpo /main/DUT/pll25dac_sclk_o
add wave -noupdate -group SvecTpo /main/DUT/pll25dac_sync_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_pll_sclk_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_pll_sdi_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_pll_cs_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_pll_dac_sync_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_pll_sdo_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_pll_status_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_125m_clk_p_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_125m_clk_n_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_acam_refclk_p_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_acam_refclk_n_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_start_from_fpga_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_err_flag_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_int_flag_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_start_dis_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_stop_dis_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_data_bus_io
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_address_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_cs_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_oe_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_rd_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_wr_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_ef1_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_ef2_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_enable_inputs_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_term_en_1_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_term_en_2_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_term_en_3_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_term_en_4_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_term_en_5_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_one_wire_b
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_scl_b
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_sda_b
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_led_status_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_led_trig1_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_led_trig2_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_led_trig3_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_led_trig4_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_led_trig5_o
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_in_fpga_1_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_in_fpga_2_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_in_fpga_3_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_in_fpga_4_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_tdc_in_fpga_5_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_start_p_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_start_n_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_clk_ref_p_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_clk_ref_n_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_trig_a_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_cal_pulse_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_d_b
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_emptyf_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_alutrigger_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_wr_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_rd_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_oe_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_led_trig_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_start_dis_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_stop_dis_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_spi_cs_dac_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_spi_cs_pll_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_spi_cs_gpio_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_spi_sclk_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_spi_mosi_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_spi_miso_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_delay_len_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_delay_val_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_delay_pulse_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_dmtd_clk_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_dmtd_fb_in_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_dmtd_fb_out_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_pll_status_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_ext_rst_n_o
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_onewire_b
add wave -noupdate -group SvecTpo /main/DUT/fmc0_prsntm2c_n_i
add wave -noupdate -group SvecTpo /main/DUT/fmc0_scl_b
add wave -noupdate -group SvecTpo /main/DUT/fmc0_sda_b
add wave -noupdate -group SvecTpo /main/DUT/fmc1_prsntm2c_n_i
add wave -noupdate -group SvecTpo /main/DUT/fmc1_scl_b
add wave -noupdate -group SvecTpo /main/DUT/fmc1_sda_b
add wave -noupdate -group SvecTpo /main/DUT/tempid_dq_b
add wave -noupdate -group SvecTpo /main/DUT/uart_rxd_i
add wave -noupdate -group SvecTpo /main/DUT/uart_txd_o
add wave -noupdate -group SvecTpo /main/DUT/clk_sys
add wave -noupdate -group SvecTpo /main/DUT/rst_n
add wave -noupdate -group SvecTpo -expand -subitemconfig {/main/DUT/fmc_host_wb_out(0) -expand /main/DUT/fmc_host_wb_out(1) -expand} /main/DUT/fmc_host_wb_out
add wave -noupdate -group SvecTpo /main/DUT/fmc_dp_wb_out
add wave -noupdate -group SvecTpo -expand -subitemconfig {/main/DUT/fmc_host_wb_in(0) -expand} /main/DUT/fmc_host_wb_in
add wave -noupdate -group SvecTpo /main/DUT/fmc_dp_wb_in
add wave -noupdate -group SvecTpo /main/DUT/fmc_host_irq
add wave -noupdate -group SvecTpo /main/DUT/tdc_clk_125m
add wave -noupdate -group SvecTpo /main/DUT/tm_link_up
add wave -noupdate -group SvecTpo /main/DUT/tm_dac_value
add wave -noupdate -group SvecTpo /main/DUT/tm_dac_wr
add wave -noupdate -group SvecTpo /main/DUT/tm_clk_aux_lock_en
add wave -noupdate -group SvecTpo /main/DUT/tm_clk_aux_locked
add wave -noupdate -group SvecTpo /main/DUT/tm_time_valid
add wave -noupdate -group SvecTpo /main/DUT/tm_tai
add wave -noupdate -group SvecTpo /main/DUT/tm_cycles
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_start
add wave -noupdate -group SvecTpo /main/DUT/ddr1_pll_reset
add wave -noupdate -group SvecTpo /main/DUT/ddr1_pll_locked
add wave -noupdate -group SvecTpo /main/DUT/dcm1_clk_ref_0
add wave -noupdate -group SvecTpo /main/DUT/dcm1_clk_ref_180
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_pll_status
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_data_out
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_data_in
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_tdc_data_oe
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_owr_en
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_owr_in
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_scl_out
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_scl_in
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_sda_out
add wave -noupdate -group SvecTpo /main/DUT/fmc1_fd_sda_in
add wave -noupdate -group SvecTpo -expand /main/DUT/fmc1_wb_out
add wave -noupdate -group SvecTpo -expand /main/DUT/fmc1_wb_in
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/clk_sys_i
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/rst_n_i
add wave -noupdate -group Mux -expand -subitemconfig {/main/DUT/U_FMC1_WB_Mux/slave_i(1) -expand /main/DUT/U_FMC1_WB_Mux/slave_i(0) -expand} /main/DUT/U_FMC1_WB_Mux/slave_i
add wave -noupdate -group Mux -expand -subitemconfig {/main/DUT/U_FMC1_WB_Mux/slave_o(1) -expand /main/DUT/U_FMC1_WB_Mux/slave_o(0) -expand} /main/DUT/U_FMC1_WB_Mux/slave_o
add wave -noupdate -group Mux -expand -subitemconfig {/main/DUT/U_FMC1_WB_Mux/master_i(0) -expand} /main/DUT/U_FMC1_WB_Mux/master_i
add wave -noupdate -group Mux -expand -subitemconfig {/main/DUT/U_FMC1_WB_Mux/master_o(0) -expand} /main/DUT/U_FMC1_WB_Mux/master_o
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/master_ie
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/master_oe
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/virtual_ERR
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/matrix_old
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/matrix_new
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/granted
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/c_mask
add wave -noupdate -group Mux /main/DUT/U_FMC1_WB_Mux/c_address
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/rst_n_a_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/rst_n_sys_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_sys_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_20m_vcxo_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_125m_pllref_p_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_125m_pllref_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_125m_gtp_p_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_125m_gtp_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_led_line_oen_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_led_line_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_led_column_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio1_a2b_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio2_a2b_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio34_a2b_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio1_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio2_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio3_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fp_gpio4_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_AS_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_RST_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_WRITE_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_AM_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DS_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_GA_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_BERR_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DTACK_n_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_RETRY_n_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_RETRY_OE_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_LWORD_n_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_ADDR_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DATA_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_BBSY_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_IRQ_n_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_IACK_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_IACKIN_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_IACKOUT_n_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DTACK_OE_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DATA_DIR_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DATA_OE_N_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_ADDR_DIR_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_ADDR_OE_N_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_txp_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_txn_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_rxp_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_rxn_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_mod_def0_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_mod_def1_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_mod_def2_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_rate_select_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_tx_fault_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_tx_disable_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_los_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pll20dac_din_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pll20dac_sclk_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pll20dac_sync_n_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pll25dac_din_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pll25dac_sclk_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pll25dac_sync_n_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_prsntm2c_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_prsntm2c_n_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tempid_dq_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/uart_rxd_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/uart_txd_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_clk_aux_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_host_wb_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_host_wb_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_dp_wb_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_dp_wb_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc0_host_irq_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_clk_aux_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_host_wb_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_host_wb_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_dp_wb_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_dp_wb_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/fmc1_host_irq_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_link_up_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_dac_value_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_dac_wr_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_clk_aux_lock_en_i
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_clk_aux_locked_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_time_valid_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_tai_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_cycles_o
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/carrier_scl_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/carrier_sda_b
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DATA_b_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_ADDR_b_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_LWORD_n_b_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_DATA_DIR_int
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/VME_ADDR_DIR_int
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/dac_hpll_load_p1
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/dac_dpll_load_p1
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/dac_hpll_data
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/dac_dpll_data
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_tx_data
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_tx_k
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_tx_disparity
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_tx_enc_err
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_rx_data
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_rx_rbclk
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_rx_k
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_rx_enc_err
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_rx_bitslide
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_rst
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/phy_loopen
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/cnx_master_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/cnx_master_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/cnx_slave_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/cnx_slave_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrn_fmc0_wb_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrn_fmc1_wb_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_aux_master_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrn_fmc0_wb_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrn_fmc1_wb_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_aux_master_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_link_up
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_tai
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_cycles
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_time_valid
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_clk_aux_lock_en
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_clk_aux_locked
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_dac_value
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm_dac_wr
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_scl_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_scl_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_sda_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_sda_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_scl_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_scl_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_sda_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sfp_sda_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_owr_en
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrc_owr_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pllout_clk_sys
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pllout_clk_dmtd
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pllout_clk_fb_pllref
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pllout_clk_fb_dmtd
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_20m_vcxo_buf
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_125m_pllref
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_125m_gtp
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_sys
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/clk_dmtd
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/local_reset_n
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/wrn_irq
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pins
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pps
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/vic_master_irq
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/ebm_src_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/ebm_src_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/ebs_snk_in
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/ebs_snk_out
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/powerup_reset_cnt
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/powerup_rst_n
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/sys_locked
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/led_state
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pps_led
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/pps_ext
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/led_link
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/led_act
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/vme_access
add wave -noupdate -group Tmpl /main/DUT/U_Node_Template/tm
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/clk_sys_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/rst_sys_n_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/rst_n_a_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_sclk_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_sdi_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_cs_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_dac_sync_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_sdo_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_status_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_clk_125m_p_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_clk_125m_n_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/acam_refclk_p_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/acam_refclk_n_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/start_from_fpga_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/err_flag_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/int_flag_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/start_dis_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/stop_dis_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/data_bus_io
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/address_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/cs_n_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/oe_n_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/rd_n_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/wr_n_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/ef1_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/ef2_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/enable_inputs_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/term_en_1_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/term_en_2_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/term_en_3_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/term_en_4_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/term_en_5_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_led_status_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_led_trig1_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_led_trig2_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_led_trig3_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_led_trig4_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_led_trig5_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_in_fpga_1_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_in_fpga_2_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_in_fpga_3_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_in_fpga_4_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_in_fpga_5_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/mezz_scl_b
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/mezz_sda_b
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/mezz_one_wire_b
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_link_up_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_time_valid_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_cycles_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_tai_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_clk_aux_lock_en_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_clk_aux_locked_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_clk_dmtd_locked_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_dac_value_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tm_dac_wr_i
add wave -noupdate -group TDCore -expand /main/DUT/U_TDC_Core/slave_i
add wave -noupdate -group TDCore -expand /main/DUT/U_TDC_Core/slave_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/direct_slave_i
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/direct_slave_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/irq_o
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/clk_62m5_sys
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/clk_125m_mezz
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/rst_125m_mezz_n
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/rst_125m_mezz
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/acam_refclk_r_edge_p
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/send_dac_word_p
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/dac_word
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_sclk
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_sdi
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/pll_dac_sync
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_slave_in
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_slave_out
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/fmc_eic_irq
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/fmc_eic_irq_synch
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_scl_out
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_scl_oen
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_sda_out
add wave -noupdate -group TDCore /main/DUT/U_TDC_Core/tdc_sda_oen
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/clk_sys_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/acam_refclk_p_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/acam_refclk_n_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/tdc_125m_clk_p_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/tdc_125m_clk_n_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_status_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_sdo_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/rst_n_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/send_dac_word_p_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/dac_word_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/wrabbit_dac_value_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/wrabbit_dac_wr_p_i
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/tdc_125m_clk_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/internal_rst_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_cs_n_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_dac_sync_n_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_sdi_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_sclk_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/acam_refclk_r_edge_p_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_status_o
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/nxt_config_st
add wave -noupdate -group ClkMgr -height 16 /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/config_st
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/config_reg
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/addr
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_word_being_sent
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_bit_being_sent
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/dac_bit_being_sent
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/bit_being_sent
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_bit_index
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_byte_index
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/dac_bit_index
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/dac_word
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/send_dac_word_r_edge_p
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/dac_only
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_cs_n
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/dac_cs_n
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/pll_status_synch
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/internal_rst_synch
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/rst_in_synch
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/acam_refclk_synch
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/send_dac_word_p_synch
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/tdc_clk_buf
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/tdc_clk
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/acam_refclk
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/rst
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/rst_cnt
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/sclk
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/sclk_r_edge
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/sclk_f_edge
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/sclk_d1
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/sclk_d2
add wave -noupdate -group ClkMgr /main/DUT/U_TDC_Core/cmp_tdc_clks_rsts_mgment/divider
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/slave_clk_i
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/slave_rst_n_i
add wave -noupdate -group Clxcross -expand /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/slave_i
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/slave_o
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/master_clk_i
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/master_rst_n_i
add wave -noupdate -group Clxcross -expand /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/master_i
add wave -noupdate -group Clxcross -expand /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/master_o
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/msend
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mrecv
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/msend_vect
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mrecv_vect
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mw_en
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mr_empty
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mr_en
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/ssend
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/srecv
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/ssend_vect
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/srecv_vect
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/sw_en
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/sr_empty
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/sr_en
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/slave_CYC
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/master_o_STB
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/slave_o_PUSH
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mpushed
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/mpopped
add wave -noupdate -group Clxcross /main/DUT/U_TDC_Core/cmp_tdc_clk_crossing/full
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/clk_sys_i
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/rst_n_i
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/slave_i
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/slave_o
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/master_i
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/master_o
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/r_slave
add wave -noupdate -expand -group TimingBreaker /main/DUT/U_TDC_Core/cmp_tdc_mezz/cmp_xwb_reg/r_master
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {519994905 ps} 0}
configure wave -namecolwidth 392
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {493102316 ps} {523923036 ps}
