files=[	"d3s_phase_encoder.vhd",
	"d3s_phase_decoder.vhd",
	"adc_serdes.vhd",
	"wr_d3s_adc.vhd", 
	"coregen/cordic_v4_0.vhd", 
	"coregen/fir_compiler_v5_0.vhd",
	"gc_delay_line.vhd",
	"coregen/cordic_v4_0.ngc", 
	"coregen/fir_compiler_v5_0.ngc", 
	"wr_d3s_adc_slave.vhd", 
	"wr_d3s_adc_wb.vhd", 
	"wr_d3s_adc_wbgen2_pkg.vhd",
	"wr_d3s_adc_slave_wb.vhd", 
	"wr_d3s_adc_slave_wbgen2_pkg.vhd",
	"d3s_acq_buffer.vhd",
	"d3s_acq_buffer_wb.vhd",
	"d3s_acq_buffer_wbgen2_pkg.vhd",
        "d3s_predecode.vhd",
	"dc_block/dc_block.vhd",
	"dc_block/MovingAvg.vhd",
       "dc_block/vector_fifo.vhd",
       "d3s_upsample.v",
       "d3s_lut.v"];



