/*
  Register definitions for slave core: WR D3S WB (slave)

  * File           : wr_d3s_adc_slave.h
  * Author         : auto-generated by wbgen2 from wr_d3s_adc_slave.wb
  * Created        : Mon Jul 25 15:07:17 2016
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE wr_d3s_adc_slave.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_WR_D3S_ADC_SLAVE_WB
#define __WBGEN2_REGDEFS_WR_D3S_ADC_SLAVE_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Reset Register */

/* definitions for field: FPGA REF/Serdes PLL Reset in reg: Reset Register */
#define D3SS_RSTR_PLL_RST                     WBGEN2_GEN_MASK(0, 1)

/* definitions for register: GPIO register */

/* definitions for field: System PLL CS in reg: GPIO register */
#define D3SS_GPIOR_PLL_SYS_CS_N               WBGEN2_GEN_MASK(0, 1)

/* definitions for field: System Reset in reg: GPIO register */
#define D3SS_GPIOR_PLL_SYS_RESET_N            WBGEN2_GEN_MASK(1, 1)

/* definitions for field: PLL SCLK (shared) in reg: GPIO register */
#define D3SS_GPIOR_PLL_SCLK                   WBGEN2_GEN_MASK(2, 1)

/* definitions for field: PLL SDIO (shared) in reg: GPIO register */
#define D3SS_GPIOR_PLL_SDIO                   WBGEN2_GEN_MASK(3, 1)

/* definitions for field: PLL SDIO direction (shared) in reg: GPIO register */
#define D3SS_GPIOR_PLL_SDIO_DIR               WBGEN2_GEN_MASK(4, 1)

/* definitions for field: VCXO PLL Reset in reg: GPIO register */
#define D3SS_GPIOR_PLL_VCXO_RESET_N           WBGEN2_GEN_MASK(5, 1)

/* definitions for field: VCXO PLL Chip Select in reg: GPIO register */
#define D3SS_GPIOR_PLL_VCXO_CS_N              WBGEN2_GEN_MASK(6, 1)

/* definitions for field: VCXO PLL SDO in reg: GPIO register */
#define D3SS_GPIOR_PLL_VCXO_SDO               WBGEN2_GEN_MASK(7, 1)

/* definitions for field: ADF4002 Chip Enable in reg: GPIO register */
#define D3SS_GPIOR_ADF_CE                     WBGEN2_GEN_MASK(8, 1)

/* definitions for field: ADF4002 Clock in reg: GPIO register */
#define D3SS_GPIOR_ADF_CLK                    WBGEN2_GEN_MASK(9, 1)

/* definitions for field: ADF4002 Latch Enable in reg: GPIO register */
#define D3SS_GPIOR_ADF_LE                     WBGEN2_GEN_MASK(10, 1)

/* definitions for field: ADF4002 Data in reg: GPIO register */
#define D3SS_GPIOR_ADF_DATA                   WBGEN2_GEN_MASK(11, 1)

/* definitions for field: Serdes PLL locked in reg: GPIO register */
#define D3SS_GPIOR_SERDES_PLL_LOCKED          WBGEN2_GEN_MASK(12, 1)

/* definitions for register: Control Reg */

/* definitions for field: ENABLE in reg: Control Reg */
#define D3SS_CR_ENABLE                        WBGEN2_GEN_MASK(0, 1)

/* definitions for register: Reconstruction delay(coarse) */

/* definitions for register: FIFO 'Phase Data FIFO' data input register 0 */

/* definitions for field: Timestamp in reg: FIFO 'Phase Data FIFO' data input register 0 */
#define D3SS_PHFIFO_R0_TSTAMP_MASK            WBGEN2_GEN_MASK(0, 28)
#define D3SS_PHFIFO_R0_TSTAMP_SHIFT           0
#define D3SS_PHFIFO_R0_TSTAMP_W(value)        WBGEN2_GEN_WRITE(value, 0, 28)
#define D3SS_PHFIFO_R0_TSTAMP_R(reg)          WBGEN2_GEN_READ(reg, 0, 28)

/* definitions for field: Run Length Enable in reg: FIFO 'Phase Data FIFO' data input register 0 */
#define D3SS_PHFIFO_R0_IS_RL                  WBGEN2_GEN_MASK(28, 1)

/* definitions for register: FIFO 'Phase Data FIFO' data input register 1 */

/* definitions for field: Run Length in reg: FIFO 'Phase Data FIFO' data input register 1 */
#define D3SS_PHFIFO_R1_RL_LENGTH_MASK         WBGEN2_GEN_MASK(0, 16)
#define D3SS_PHFIFO_R1_RL_LENGTH_SHIFT        0
#define D3SS_PHFIFO_R1_RL_LENGTH_W(value)     WBGEN2_GEN_WRITE(value, 0, 16)
#define D3SS_PHFIFO_R1_RL_LENGTH_R(reg)       WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for register: FIFO 'Phase Data FIFO' data input register 2 */

/* definitions for field: Phase in reg: FIFO 'Phase Data FIFO' data input register 2 */
#define D3SS_PHFIFO_R2_RL_PHASE_MASK          WBGEN2_GEN_MASK(0, 32)
#define D3SS_PHFIFO_R2_RL_PHASE_SHIFT         0
#define D3SS_PHFIFO_R2_RL_PHASE_W(value)      WBGEN2_GEN_WRITE(value, 0, 32)
#define D3SS_PHFIFO_R2_RL_PHASE_R(reg)        WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: FIFO 'Phase Data FIFO' control/status register */

/* definitions for field: FIFO full flag in reg: FIFO 'Phase Data FIFO' control/status register */
#define D3SS_PHFIFO_CSR_FULL                  WBGEN2_GEN_MASK(16, 1)

/* definitions for field: FIFO empty flag in reg: FIFO 'Phase Data FIFO' control/status register */
#define D3SS_PHFIFO_CSR_EMPTY                 WBGEN2_GEN_MASK(17, 1)

/* definitions for field: FIFO clear in reg: FIFO 'Phase Data FIFO' control/status register */
#define D3SS_PHFIFO_CSR_CLEAR_BUS             WBGEN2_GEN_MASK(18, 1)

/* definitions for field: FIFO counter in reg: FIFO 'Phase Data FIFO' control/status register */
#define D3SS_PHFIFO_CSR_USEDW_MASK            WBGEN2_GEN_MASK(0, 14)
#define D3SS_PHFIFO_CSR_USEDW_SHIFT           0
#define D3SS_PHFIFO_CSR_USEDW_W(value)        WBGEN2_GEN_WRITE(value, 0, 14)
#define D3SS_PHFIFO_CSR_USEDW_R(reg)          WBGEN2_GEN_READ(reg, 0, 14)
/* [0x0]: REG Reset Register */
#define D3SS_REG_RSTR 0x00000000
/* [0x4]: REG GPIO register */
#define D3SS_REG_GPIOR 0x00000004
/* [0x8]: REG Control Reg */
#define D3SS_REG_CR 0x00000008
/* [0xc]: REG Reconstruction delay(coarse) */
#define D3SS_REG_REC_DELAY_COARSE 0x0000000c
/* [0x10]: REG FIFO 'Phase Data FIFO' data input register 0 */
#define D3SS_REG_PHFIFO_R0 0x00000010
/* [0x14]: REG FIFO 'Phase Data FIFO' data input register 1 */
#define D3SS_REG_PHFIFO_R1 0x00000014
/* [0x18]: REG FIFO 'Phase Data FIFO' data input register 2 */
#define D3SS_REG_PHFIFO_R2 0x00000018
/* [0x1c]: REG FIFO 'Phase Data FIFO' control/status register */
#define D3SS_REG_PHFIFO_CSR 0x0000001c
#endif
