---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for TOF
---------------------------------------------------------------------------------------
-- File           : ../core/TrevGen_wb_slave_pkg.vhd
-- Author         : auto-generated by wbgen2 from TrevGen_wb_slave.wb
-- Created        : Thu Jun 16 16:54:34 2016
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE TrevGen_wb_slave.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package TOF_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_TOF_in_registers is record
    end record;
  
  constant c_TOF_in_registers_init_value: t_TOF_in_registers := (
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_TOF_out_registers is record
      tof_mintrev_o                            : unsigned(30 downto 0);
      tof_maxtrev_o                            : unsigned(30 downto 0);
      tof_ctrl_wrltcy_o                        : unsigned(19 downto 0);
      tof_ctrl_gmargin_o                       : unsigned(1 downto 0);
      tof_ctrl_gwidth_o                        : unsigned(1 downto 0);
      end record;
    
    constant c_TOF_out_registers_init_value: t_TOF_out_registers := (
      tof_mintrev_o => (others => '0'),
      tof_maxtrev_o => (others => '0'),
      tof_ctrl_wrltcy_o => (others => '0'),
      tof_ctrl_gmargin_o => (others => '0'),
      tof_ctrl_gwidth_o => (others => '0')
      );
    function "or" (left, right: t_TOF_in_registers) return t_TOF_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body TOF_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if x = '1' then
return '1';
else
return '0';
end if;
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_TOF_in_registers) return t_TOF_in_registers is
variable tmp: t_TOF_in_registers;
begin
return tmp;
end function;
end package body;
