files = [ "wrn_mqueue_host.vhd",
          "wrn_mqueue_remote.vhd",
          "mt_rmq_outgoing_slot.vhd",
          "mt_rmq_incoming_slot.vhd",
#          "wrn_mqueue_remote_noeb.vhd",
#          "wrn_mqueue_etherbone_output.vhd",
          "wrn_mqueue_irq_unit.vhd",
          "wrn_mqueue_pkg.vhd",
          "wrn_mqueue_slot.vhd",
          "mt_mqueue_remote.vhd",
          "wrn_eb_cycle_gen.vhd",
          "wrn_mqueue_wishbone_slave.vhd",
          "mt_ethernet_tx_framer.vhd",
          "mt_rmq_rx_deframer.vhd",
          "mt_rmq_rx_path.vhd",
          "mt_rmq_tx_path.vhd",
          "mt_stream_register.vhd",
          "mt_udp_tx_framer.vhd",
          "mt_rmq_packet_output.vhd",
          "mt_wr_sink.vhd",
          "mt_wr_source.vhd"];
