files = [ "mt_mqueue_host.vhd",
          "mt_mqueue_remote.vhd",
          "mt_rmq_outgoing_slot.vhd",
          "mt_rmq_incoming_slot.vhd",
          "mt_mqueue_irq_unit.vhd",
          "mt_mqueue_pkg.vhd",
          "mt_mqueue_slot.vhd",
          "mt_mqueue_remote.vhd",
          "mt_mqueue_wishbone_slave.vhd",
          "mt_ethernet_tx_framer.vhd",
          "mt_rmq_rx_deframer.vhd",
          "mt_rmq_rx_path.vhd",
          "mt_rmq_tx_path.vhd",
          "mt_stream_register.vhd",
          "mt_udp_tx_framer.vhd",
          "mt_rmq_packet_output.vhd",
          "mt_wr_sink.vhd",
          "mt_wr_source.vhd"];
